spring:
  application:
    name: profile-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: tuan6326
server:
  port: 8081
  servlet:
    context-path: /profile
